a="vasu manish sai shiva kiran pavi anu are friends"
print(a)
print(len(a))
print(type(a))
print(a.count(""))
print(a.upper())
print(a.lower())
print(a.split())
print(a.endswith("friends"))
print(a.replace("friends","best friends"))
print(a.title())
print(a.startswith("vasu"))
print(a.encode())
print(a.find('k'))
print("".join(reversed(a)))
print(a[0])
